#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

try:
    import tomllib  # Python 3.11+
except ModuleNotFoundError:  # pragma: no cover
    try:
        import tomli as tomllib
    except ModuleNotFoundError as exc:  # pragma: no cover
        print("tomllib is unavailable. Use Python 3.11+ or `pip install tomli`.", file=sys.stderr)
        raise SystemExit(1) from exc

ROOT = Path(__file__).resolve().parents[1]
CONFIG_PATH = ROOT / "zensical.toml"
OUTPUT_PATH = ROOT / "frontend" / "lib" / "nav.js"


def href_from_markdown(path: str) -> str:
    normalized = path.replace("\\", "/")
    if not normalized.endswith(".md"):
        raise ValueError(f"Expected markdown path, got: {path}")
    normalized = normalized[: -len(".md")]
    if normalized == "index":
        return "/"
    if normalized.endswith("/index"):
        normalized = normalized[: -len("/index")]
    return "/" + normalized


def build_nav(data: dict) -> list[dict]:
    nav_entries = data.get("project", {}).get("nav", [])
    if not isinstance(nav_entries, list):
        raise ValueError("zensical.toml project.nav must be a list")

    nav = []
    for entry in nav_entries:
        if not isinstance(entry, dict) or len(entry) != 1:
            raise ValueError(f"Invalid nav entry: {entry!r}")
        section, value = next(iter(entry.items()))

        items = []
        if isinstance(value, str):
            items.append({"label": section, "href": href_from_markdown(value)})
        elif isinstance(value, list):
            for item in value:
                if not isinstance(item, dict) or len(item) != 1:
                    raise ValueError(f"Invalid nav item in {section}: {item!r}")
                label, md_path = next(iter(item.items()))
                items.append({"label": label, "href": href_from_markdown(md_path)})
        else:
            raise ValueError(f"Invalid nav value for {section}: {value!r}")

        nav.append({"section": section, "items": items})

    return nav


def render_nav_js(nav: list[dict]) -> str:
    nav_json = json.dumps(nav, indent=2)
    header = "// This file is auto-generated by scripts/sync_nav.py. Do not edit manually.\n"
    footer = """

export const flatNavItems = nav.flatMap((section) => section.items.map((item) => ({ ...item, section: section.section })));

export function normalizeHref(href) {
  if (href === "/") {
    return "/";
  }
  return href.replace(/\/$/, "");
}

export function getPrevNext(currentHref) {
  const normalized = normalizeHref(currentHref);
  const items = flatNavItems.map((item) => ({
    ...item,
    href: normalizeHref(item.href),
  }));
  const index = items.findIndex((item) => item.href === normalized);
  if (index === -1) {
    return { prev: null, next: null };
  }
  return {
    prev: index > 0 ? items[index - 1] : null,
    next: index < items.length - 1 ? items[index + 1] : null,
  };
}
""".lstrip()

    return f"{header}\nexport const nav = {nav_json};\n{footer}"


def main() -> int:
    parser = argparse.ArgumentParser(description="Sync zensical.toml nav to frontend/lib/nav.js")
    parser.add_argument("--check", action="store_true", help="Fail if nav.js is out of date")
    args = parser.parse_args()

    if not CONFIG_PATH.exists():
        print(f"Missing config: {CONFIG_PATH}", file=sys.stderr)
        return 1

    data = tomllib.loads(CONFIG_PATH.read_text(encoding="utf-8"))
    nav = build_nav(data)
    nav_js = render_nav_js(nav)

    if args.check:
        if not OUTPUT_PATH.exists():
            print("nav.js missing. Run scripts/sync_nav.py", file=sys.stderr)
            return 1
        current = OUTPUT_PATH.read_text(encoding="utf-8")
        if current != nav_js:
            print("nav.js is out of date. Run scripts/sync_nav.py", file=sys.stderr)
            return 1
        return 0

    OUTPUT_PATH.write_text(nav_js, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
